### ISSUE TITLE
Won't compile in Xcode 6.4 because of missing "extern" keywords

### ISSUE THREAD

**Issue by tempelmann** [aburgh/Disk-Arbitrator#12]
I just tried to build the master in Xcode 6.4 after removing the code signing settings and changing deployment to 10.10.

I got a few "duplicate symbols" errors then. The issue is in "DiskArbitratorAppController+Toolbar.h" where the ToolbarItem... declarations need to have an "extern" modifier added as follows:

// Toolbar Item Identifier constants
extern NSString * const ToolbarItemMainIdentifier;
extern NSString * const ToolbarItemInfoIdentifier;
extern NSString * const ToolbarItemMountIdentifier;
extern NSString * const ToolbarItemEjectIdentifier;
extern NSString * const ToolbarItemAttachDiskImageIdentifier;

**Comment by kainjow** [comment]
Fixed in 75104ef60881130217bc09723b65c8100ce7f8cb
